### PR TITLE
Update unary with complex CAPS

### PR DESCRIPTION
**Pull request by aaronviets**
Hi Leo,

Hopefully this is better. Sorry about the large number of commits, I'm still figuring out git.

-Aaron

### CODE REVIEW

**Comment by lpsinger** [comment]
I'm not crazy about dropping inheritance from GstAudioFilter. Is that necessary? What if you had an element that converted between complex and stereo?

**Comment by aaronviets** [comment]
Hi Leo,
The element gstlal_togglecomplex converts between complex and sterio. Currently, the calibration pipeline splits complex data into two real streams to manipulate separately, but it could be made more efficient if the elements (pow in particular) could handle complex formats. I tried several ways to add complex CAPS without abandoning GstAudioFilter, and the caps could not be negotiated. I added the formats “Z64” and “Z128” to the caps, but because GstAudioFilter doesn’t recognize those, it still would not negotiate. One thought would be to have both versions of the package available (one based on GstAudioFilter and one with complex caps).
-Aaron

**Comment by lpsinger** [comment]
Have you tried asking the GStreamer developers if they would officially support complex caps? Maybe LIGO's suddenly very high profile could give you guys some leverage to ask for more science-friendly features in the main code base.

**Comment by aaronviets** [comment]
I have not tried that. That would certainly make things easier for us. But I’m afraid we won’t be able to wait for GStreamer to add support for complex caps with ER9 and O2 coming up soon. I can ask Kipp or Chad whether they know if such a request has been made recently.

**Comment by lpsinger** [comment]
OK, let me take some time to study the source code for GstAudioFilter. Looks like gstreamer.freedesktop.org is down right now.

**Comment by lpsinger** [comment]
@aaronviets, what about #4? That adds support for complex numbers without disinheriting from `GstAudioFilter` or relying on caps that are not supported in the GStreamer core. Admittedly, you'll still have to wrap the element in a pair of `lal_togglecomplex` elements. But this patch would get you back in business right away.

**Pull request closed without merging**
